input:
  volume:
    "data/test/first_children/531960/SUV.nii.gz"
  ct_volume: null

output:
  dir: outputs/inference
  save_preview_gif: true
  preview_gif_duration_ms: 80

checkpoint:
  path: checkpoints/exp_unet3d_free_data_lymphoma_HD95_AVD_holdout_20260328_203311/best_model.pth

sliding_window:
  patch_size: [96, 96, 96]
  overlap: 0.5
  batch_size: 4

device: cuda
num_classes: 2
