defaults:
  - data: pet
  - inference: sliding_window
  - model: unet3d
  - training: baseline
  - logging: mlflow
  - _self_

hydra: # don't save outputs to a new directory
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false